/* Tela de Cadastro, foi a primeira parte a ser pensada por nós, pois ela foi o
 * princípio para nos prosseguirmos com a criação do nosso jogo.
 * 
 * 
 */
package br.com.Attack.formularios;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Konex Soluções Tecnológicas.
 */
public class Cadastro extends javax.swing.JFrame {
    public static String usuario;
    public static String senhaUsuario;
    public static String emailUsuario;

    /**
     * Creates new form TelaInicial
     */
    

    private void TelaTutorial(){
        
	Tutorial tutorial = new Tutorial();
        tutorial.setVisible(true);
        dispose();		
    }
    
    private void TelaLogin(){
        
	Login login = new Login();
        login.setVisible(true);
        dispose();		
    }
    
    public Cadastro() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TextSenha = new javax.swing.JLabel();
        TextEmail = new javax.swing.JLabel();
        TextNome = new javax.swing.JLabel();
        TextParaComecar = new javax.swing.JLabel();
        CampoEmail = new javax.swing.JTextField();
        CampoNomeUsuario = new javax.swing.JTextField();
        CampoSenha = new javax.swing.JPasswordField();
        btnAvancar = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Criar Conta");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextSenha.setForeground(new java.awt.Color(255, 255, 255));
        TextSenha.setText("Senha:");
        getContentPane().add(TextSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        TextEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextEmail.setForeground(new java.awt.Color(255, 255, 255));
        TextEmail.setText("E-Mail:");
        getContentPane().add(TextEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        TextNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextNome.setForeground(new java.awt.Color(255, 255, 255));
        TextNome.setText("Nome:");
        getContentPane().add(TextNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        TextParaComecar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextParaComecar.setForeground(new java.awt.Color(255, 255, 255));
        TextParaComecar.setText("Para começar a vamos criar um conta Attack");
        getContentPane().add(TextParaComecar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        CampoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoEmailActionPerformed(evt);
            }
        });
        getContentPane().add(CampoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 240, 30));

        CampoNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomeUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(CampoNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 240, 30));
        getContentPane().add(CampoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 240, 30));

        btnAvancar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Attack/icones/btnAvancar.png"))); // NOI18N
        btnAvancar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAvancarMouseReleased(evt);
            }
        });
        getContentPane().add(btnAvancar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, -1, -1));

        Fundo.setForeground(new java.awt.Color(255, 255, 255));
        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Attack/icones/TelaLogin.png"))); // NOI18N
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CampoNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomeUsuarioActionPerformed

    private void btnAvancarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAvancarMouseReleased
        usuario = (CampoNomeUsuario.getText());
        emailUsuario = (CampoEmail.getText());
        senhaUsuario = (CampoSenha.getText());
                            
                            
        if(!"".equals(usuario) && !"".equals(emailUsuario) && !"".equals(senhaUsuario)){
            JOptionPane.showMessageDialog(null, "Bem vindo " + usuario + "! Agora "
            + "que você já tem uma conta no Attack, vamos aprender como se joga!");
                TelaTutorial();
        }else{
            JOptionPane.showMessageDialog(null, "Por favor Preencha todos os "
                    + "Campos","Importante!", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnAvancarMouseReleased

    private void CampoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
                
            }
        });
        
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoEmail;
    private javax.swing.JTextField CampoNomeUsuario;
    private javax.swing.JPasswordField CampoSenha;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel TextEmail;
    private javax.swing.JLabel TextNome;
    private javax.swing.JLabel TextParaComecar;
    private javax.swing.JLabel TextSenha;
    private javax.swing.JLabel btnAvancar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
