/*
 * Essa classe foi criada para puxarmos todas as informações pessoais e escolhidas
 * pelo o usuário. Com essa classe nos conseguimos realizar as partidas.
 * 
 */
package br.com.Attack.formularios;

import java.awt.event.ActionListener;
import javafx.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Konex Soluções Tecnológicas.
 */

public class InformacaoPessoal extends javax.swing.JFrame {
    public static int idadeF;
    public static int idadeM;
    public static String sexoM;
    public static String sexoF;
    public static int idadeG;
    
    
       private void PublicoM(){
        
	PublicoM publicom = new PublicoM();
        publicom.setVisible(true);
        dispose();		
    }
       
       private void PublicoF(){
        
	PublicoF publicof = new PublicoF();
        publicof.setVisible(true);
        dispose();		
    }
    

    /**
     * Creates new form TelaInicio
     */
    public InformacaoPessoal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // alterar jtext
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextIdade = new javax.swing.JLabel();
        TextSexo = new javax.swing.JLabel();
        CaixaSexo = new javax.swing.JComboBox<>();
        CaixaIdade = new javax.swing.JComboBox<>();
        btnProximo = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Informações Pessoais");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextIdade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextIdade.setForeground(new java.awt.Color(255, 255, 255));
        TextIdade.setText("Selecione sua idade:");
        getContentPane().add(TextIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 130, -1));

        TextSexo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextSexo.setForeground(new java.awt.Color(255, 255, 255));
        TextSexo.setText("Selecione seu gênero:");
        getContentPane().add(TextSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        CaixaSexo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        CaixaSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione seu gênero>", "Masculino", "Feminino" }));
        CaixaSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaSexoActionPerformed(evt);
            }
        });
        getContentPane().add(CaixaSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 210, 30));

        CaixaIdade.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        CaixaIdade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione sua idade>", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "71", "73", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99" }));
        CaixaIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaIdadeActionPerformed(evt);
            }
        });
        getContentPane().add(CaixaIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 210, 30));

        btnProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Attack/icones/btnAvancar.png"))); // NOI18N
        btnProximo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnProximoMouseReleased(evt);
            }
        });
        getContentPane().add(btnProximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, -1, -1));

        Fundo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Fundo.setForeground(new java.awt.Color(255, 255, 255));
        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Attack/icones/TelaLogin.png"))); // NOI18N
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CaixaSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaixaSexoActionPerformed

    private void CaixaIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaixaIdadeActionPerformed

    private void btnProximoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProximoMouseReleased
                    if(CaixaSexo.getSelectedItem().equals("<Selecione uma das opções>")){
                        JOptionPane.showMessageDialog(null, "Opção Inválida, Selecione um Gênero! ","Importante!", JOptionPane.WARNING_MESSAGE);
                    }
                    else if(CaixaSexo.getSelectedItem().equals("Masculino")){
                        sexoM = CaixaSexo.getSelectedItem().toString();
                        idadeM = CaixaIdade.getSelectedIndex();
                        idadeG = idadeM;
                        PublicoM();
                        
               
                    }
                    else if(CaixaSexo.getSelectedItem().equals("Feminino")){
                       idadeF = CaixaIdade.getSelectedIndex();
                       sexoF = CaixaSexo.getSelectedItem().toString();
                       idadeG = idadeM;
                         PublicoF(); 
                    }
    }//GEN-LAST:event_btnProximoMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/Pacote1/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pacote1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pacote1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pacote1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pacote1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacaoPessoal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CaixaIdade;
    private javax.swing.JComboBox<String> CaixaSexo;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel TextIdade;
    private javax.swing.JLabel TextSexo;
    private javax.swing.JLabel btnProximo;
    // End of variables declaration//GEN-END:variables



}

