/*
 * Como todo o jogo possui o seu menu assim temos o menu, é forma de organizar as
 * as informações e orientar o usuário a escolher uma opção.
 * 
 */
package br.com.Attack.formularios;

import br.com.Attack.Perguntas1x1.PerguntaFilo1;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import br.com.Attack.Perguntas1x1.PerguntaSocio1;
import br.com.Attack.Perguntas1x1.PerguntaMat1;
import br.com.Attack.Perguntas2x2.PerguntaAntropologia;
import br.com.Attack.Perguntas2x2.PerguntaHistoria;
import br.com.Attack.Perguntas2x2.PerguntaIntercambio;

/**
 *
 * @author Konex Soluções Tecnológicas.
 */

public class MenuPrincipal extends javax.swing.JFrame {
    public static int chances=1;
    public static int escolhaCategoriaTotal;
    
    private InformacaoPessoal classe = new InformacaoPessoal();
    private int idade = classe.idadeG;
   
    private void TelaChat(){
        
	Chat chat = new Chat();
        chat.setVisible(true);
    }
    
    private void TelaShopping(){
        
	Shopping shop= new Shopping();
        shop.setVisible(true);
        
        
    }
    
    private void TelaLogin(){
        
	Login login = new Login();
        login.setVisible(true);
        dispose();		
    }
    
    private void TelaAlterarDados(){
        
	AlterarDados alterardados = new AlterarDados();
        alterardados.setVisible(true);
        dispose();		
    }
    
    private void TelaSobre(){
        
	Sobre sobre= new Sobre();
        sobre.setVisible(true);
        
        
    }
    
    private void TelaPerguntasSocio1(){
        
	PerguntaSocio1 pergSocio = new PerguntaSocio1();
        pergSocio.setVisible(true);
        dispose();		
    }
    
    private void TelaPerguntasFilosofia1(){
        
	PerguntaFilo1 pergFilo = new PerguntaFilo1();
        pergFilo.setVisible(true);
        dispose();		
    }
    
    private void TelaPerguntasMatematica1(){
        
	PerguntaMat1 pergMat = new PerguntaMat1();
        pergMat.setVisible(true);
        dispose();		
    }
    
    private void TelaPerguntaAntropologia(){
        
	PerguntaAntropologia pergAntro = new PerguntaAntropologia();
        pergAntro.setVisible(true);
        dispose();		
    }
    
    private void TelaPerguntaHistoria(){
        
	PerguntaHistoria pergHist = new PerguntaHistoria();
        pergHist.setVisible(true);
        dispose();		
    }
    private void TelaPerguntaIntercambio(){
        
	PerguntaIntercambio pergInter = new PerguntaIntercambio();
        pergInter.setVisible(true);
        dispose();		
    }
   
    /**
     * Creates new form Login
     */
    public MenuPrincipal() {
        initComponents();
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSair = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JLabel();
        btnChat = new javax.swing.JLabel();
        btnShop = new javax.swing.JLabel();
        btnPartida1 = new javax.swing.JLabel();
        btnSobre = new javax.swing.JLabel();
        LogoAttack = new javax.swing.JLabel();
        btnPartida2 = new javax.swing.JLabel();
        Copy = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Attack/icones/btnSair.png"))); // NOI18N
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSairMouseReleased(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, -1));

        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Attack/icones/btnAlterar.png"))); // NOI18N
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAlterarMouseReleased(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        btnChat.setForeground(new java.awt.Color(255, 255, 255));
        btnChat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Attack/icones/chat.png"))); // NOI18N
        btnChat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnChatMouseReleased(evt);
            }
        });
        getContentPane().add(btnChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        btnShop.setForeground(new java.awt.Color(255, 255, 255));
        btnShop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Attack/icones/btnShop.png"))); // NOI18N
        btnShop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnShopMouseReleased(evt);
            }
        });
        getContentPane().add(btnShop, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        btnPartida1.setForeground(new java.awt.Color(255, 255, 255));
        btnPartida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Attack/icones/btnPartida1_1.png"))); // NOI18N
        btnPartida1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPartida1MouseReleased(evt);
            }
        });
        getContentPane().add(btnPartida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        btnSobre.setForeground(new java.awt.Color(255, 255, 255));
        btnSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Attack/icones/btnSobre.png"))); // NOI18N
        btnSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSobreMouseReleased(evt);
            }
        });
        getContentPane().add(btnSobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        LogoAttack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Attack/icones/LogoAttack.png"))); // NOI18N
        getContentPane().add(LogoAttack, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        btnPartida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Attack/icones/btnPartida2_2.png"))); // NOI18N
        btnPartida2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPartida2MouseReleased(evt);
            }
        });
        getContentPane().add(btnPartida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));

        Copy.setForeground(new java.awt.Color(255, 255, 255));
        Copy.setText("copyright © 2020 todos os direitos reservados");
        getContentPane().add(Copy, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, -1, -1));

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Attack/icones/TelaAzul.png"))); // NOI18N
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseReleased
        
        switch(JOptionPane.showConfirmDialog(null,"Deseja mesmo sair da sua conta? V"
                + "ocê perderá todas as alterações não salvas ","Sair?", JOptionPane.YES_NO_OPTION)){
            case 0:
                TelaLogin();
            break;
        }
    }//GEN-LAST:event_btnSairMouseReleased

    private void btnAlterarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseReleased
        TelaAlterarDados();
    }//GEN-LAST:event_btnAlterarMouseReleased

    private void btnChatMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChatMouseReleased
        TelaChat();
    }//GEN-LAST:event_btnChatMouseReleased

    private void btnPartida1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPartida1MouseReleased
        int escolhaCategoria0 = Integer.parseInt(JOptionPane.showInputDialog("Escolha um categoria"
                     + "categorias:\n1-Sociologia \n2-Filosofia \n3-Matemática "
                     + "\n4-Física \n5-Língua Portuguesa")); 
                
                int escolhaCategoria1 = Integer.parseInt(JOptionPane.showInputDialog("Escolha outra categoria"
                     + "categorias:\n1-Sociologia \n2-Filosofia \n3-Matemática "
                     + "\n4-Física \n5-Língua Portuguesa"));
                
                int escolhaCategoria2 = Integer.parseInt(JOptionPane.showInputDialog("Escolha mais uma categoria"
                     + "categorias:\n1-Sociologia \n2-Filosofia \n3-Matemática "
                     + "\n4-Física \n5-Língua Portuguesa")); 
                    
                // Cálculo que ajuda a prever as opções
                escolhaCategoriaTotal= escolhaCategoria0+escolhaCategoria1+escolhaCategoria2;
        
        // Numeração que define as escolhas 
        if(escolhaCategoriaTotal == 6){
        
            if(idade == 17 || idade <= 99 ){
                switch(JOptionPane.showConfirmDialog(null,"PRONTO PARA "
                    + "COMEÇAR?","VAMOS COMEÇAR",JOptionPane.YES_NO_OPTION)){
                
                    case 0:
                        TelaPerguntasSocio1();
                        break;
                    
                    case 1:
                        break;    
                }
            }
        }
        
        if(escolhaCategoriaTotal == 7){
            
            if(idade == 17 ||  idade <= 99){
                switch(JOptionPane.showConfirmDialog(null,"PRONTO PARA "
                        + "COMEÇAR?","VAMOS COMEÇAR",JOptionPane.YES_NO_OPTION)){
                
                    case 0:
                        TelaPerguntasSocio1();
                        break;
                    case 1:
                        break;    
                    }
                }
            }
        
        if(escolhaCategoriaTotal == 8){
            if(idade == 17 || idade <= 22){
                switch(JOptionPane.showConfirmDialog(null,"PRONTO PARA "
                        + "COMEÇAR?","VAMOS COMEÇAR",JOptionPane.YES_NO_OPTION)){
                
                    case 0:
                        TelaPerguntasSocio1();
                        break;
                    case 1:
                        break;    
                }
            }
        }

        if(escolhaCategoriaTotal == 9){
            
            if(idade == 17 || idade <= 99){
                switch(JOptionPane.showConfirmDialog(null,"PRONTO PARA COMEÇAR?","VAMOS COMEÇAR",JOptionPane.YES_NO_OPTION)){
                
                    case 0:
                        TelaPerguntasFilosofia1();
                        break;
                    case 1:
                        break;    
                }
            }
        }
            
        if(escolhaCategoriaTotal == 10){
            
            if(idade == 17 || idade <= 99){
                switch(JOptionPane.showConfirmDialog(null,"PRONTO PARA COMEÇAR?","VAMOS COMEÇAR",JOptionPane.YES_NO_OPTION)){
                
                    case 0:
                        TelaPerguntasFilosofia1();
                        break;
                    case 1:
                        break;    
                }
            }
        }
            
        if(escolhaCategoriaTotal == 12){
            
            if(idade== 17 || idade <=99){
                switch(JOptionPane.showConfirmDialog(null,"PRONTO PARA COMEÇAR?","VAMOS COMEÇAR",JOptionPane.YES_NO_OPTION)){
                    case 0:
                        TelaPerguntasMatematica1();
                        break;
                    case 1:
                        break;    
                }
            }
        }
         
        
    }//GEN-LAST:event_btnPartida1MouseReleased

    private void btnShopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShopMouseReleased
        TelaShopping();
        dispose();
    }//GEN-LAST:event_btnShopMouseReleased

    private void btnSobreMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSobreMouseReleased
        TelaSobre();
        dispose();
    }//GEN-LAST:event_btnSobreMouseReleased

    private void btnPartida2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPartida2MouseReleased
                    int escolhaCategoria0 = Integer.parseInt(JOptionPane.showInputDialog("Escolha uma"
                    + "categoria:\n1-Antropologia \n2-História \n3-Intercâmbio "
                    + "\n4-Turismo \n5-Geografia Política"));
               
                    int escolhaCategoria1 = Integer.parseInt(JOptionPane.showInputDialog("Escolha outra"
                    + "categoria:\n1-Antropologia \n2-História \n3-Intercâmbio "
                    + "\n4-Turismo \n5-Geografia Política"));
               
                    int escolhaCategoria2 = Integer.parseInt(JOptionPane.showInputDialog("Escolha mais uma"
                    + "categoria:\n1-Antropologia \n2-História \n3-Intercâmbio "
                    + "\n4-Turismo \n5-Geografia Política"));
                   
                    escolhaCategoriaTotal= escolhaCategoria0+escolhaCategoria1+escolhaCategoria2;
                    
                    if(escolhaCategoriaTotal==6){
                        if(idade == 17 || idade <= 99){
                        switch(JOptionPane.showConfirmDialog(null,"Pronto Para começar?","Vamos lá",JOptionPane.YES_NO_OPTION)){
                           
                            case 0:
                                //Chamada Tela Pergunta
                                TelaPerguntaAntropologia();
                                break;
                               
                            case 1:
                                break;
                        }
                        }
                    }
                   
                    if(escolhaCategoriaTotal==7){
                        if(idade == 17 || idade <= 99){
                            switch(JOptionPane.showConfirmDialog(null,"Pronto Para começar?","Vamos lá",JOptionPane.YES_NO_OPTION)){
                           
                            case 0:
                                //Chamada Tela Pergunta
                                TelaPerguntaAntropologia();
                                break;
                               
                            case 1:
                                break;
                            }
                        }
                    }
                    if(escolhaCategoriaTotal==8){
                        if(idade == 17 || idade <= 99){
                            switch(JOptionPane.showConfirmDialog(null,"Pronto Para começar?","Vamos lá",JOptionPane.YES_NO_OPTION)){
                           
                            case 0:
                                //Chamada Tela Pergunta
                                TelaPerguntaAntropologia();
                                break;
                               
                            case 1:
                                break;
                            }    
                        }
                    }
                    if(escolhaCategoriaTotal==9){
                        if(idade == 17 || idade <= 24){
                            switch(JOptionPane.showConfirmDialog(null,"Pronto Para começar?","Vamos lá",JOptionPane.YES_NO_OPTION)){
                           
                            case 0:
                                //Chamada Tela Pergunta
                                TelaPerguntaHistoria();
                                break;
                               
                            case 1:
                                break;
                            }
                        }        
                    }    
                    if(escolhaCategoriaTotal==10){
                        if(idade == 17 || idade <= 99){
                        switch(JOptionPane.showConfirmDialog(null,"Pronto Para começar?","Vamos lá",JOptionPane.YES_NO_OPTION)){
                           
                            case 0:
                                //Chamada Tela Pergunta
                                TelaPerguntaHistoria();
                                break;
                               
                            case 1:
                                break;
                            }
                        }
                    }
                       
                    if(escolhaCategoriaTotal==12){
                        if(idade == 17 || idade <= 99){
                        switch(JOptionPane.showConfirmDialog(null,"Pronto Para começar?","Vamos lá",JOptionPane.YES_NO_OPTION)){
                           
                            case 0:
                                //Chamada Tela Pergunta
                                TelaPerguntaIntercambio();
                                break;
                               
                            case 1:
                                break;
                            } 
                        }
                    }
    }//GEN-LAST:event_btnPartida2MouseReleased
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Copy;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel LogoAttack;
    private javax.swing.JLabel btnAlterar;
    private javax.swing.JLabel btnChat;
    private javax.swing.JLabel btnPartida1;
    private javax.swing.JLabel btnPartida2;
    private javax.swing.JLabel btnSair;
    private javax.swing.JLabel btnShop;
    private javax.swing.JLabel btnSobre;
    // End of variables declaration//GEN-END:variables
}
