 /*
 * Da mesma forma da tela do publico feminino, também tivemos que ter uma do público
 * masculino.
 * 
 * 
 */
package br.com.Attack.formularios;

import java.awt.event.ActionListener;
import javafx.event.ActionEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Konex Soluções Tecnológicas.
 */
public class PublicoM extends javax.swing.JFrame {
    public static String PersonaUsuario;
    
    private void TelaPacote1(){
        
	Pacote1 pacote1 = new Pacote1();
        pacote1.setVisible(true);
        dispose();		
    }

    /**
     * @return the idadeF
     */
    
    /**
     * Creates new form TelaInicio
     */
    public PublicoM() {
        initComponents();
         
    }
    private InformacaoPessoal classe = new InformacaoPessoal();
    private int idadeMasculino = classe.idadeM;
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // alterar jtext
        int personaM1;
        int personaM2;
        int personaM3;
    
  public static int boasvindasPersonagemM1(int personaM1){
    int boasvindasP = 0;
    
    switch(personaM1){
        case 1:
            JOptionPane.showMessageDialog(null,"Boa escolha, esse personagem é ótimo "
                    + "em perguntas da sociedade e atualidades.");    
        break;
        
        case 2:
            JOptionPane.showMessageDialog(null,"É muito experiente "
                    + "em perguntas filosóficas, se você se identifica com filosofia "
                    + "é o personagem ideal para você.");
            
        break; 
        
        case 3:
            JOptionPane.showMessageDialog(null,"Nerd tem facilidade em resolver "
                    + "calcúlos matemáticos, se você se identifica fez a "
                    + "escolha certa");
        break; 
        
        case 4:
            JOptionPane.showMessageDialog(null," Físico, tem a super capacidade "
                    + "em resolver calcúlos físicos, se você se identifica"
                    + "fez a escolha certa");
        break;
        
        case 5:
            JOptionPane.showMessageDialog(null,"Adora o Brasil, é muito inteligente "
                    + "em língua portuguesa, se você se identifica fez a escolha certa");    
        break; 
    }
    
    
    return boasvindasP ;
    
}   
    public static int boasvindasPersonagemM2(int personaM2){
    int boasvindasP  = 0;
    
    switch(personaM2){
        case 1:
            JOptionPane.showMessageDialog(null,"Sabe tudo sobre a humanidade, "
                    + "se você se você se identifica, fez a escolha certa.");
        break;
        
        case 2:
            JOptionPane.showMessageDialog(null,"Sabe tudo sobre História, se "
                    + "você se você se identifica, fez a escolha certa.");    
        break; 
        
        case 3:
            JOptionPane.showMessageDialog(null," Então você quer fazer algumas"
                    + "viagens pelo o mundo a fora? Você fez a escolha certa.");  
        break; 
        
        case 4:
            JOptionPane.showMessageDialog(null,"Conhece tudo sobre geografia "
                    + "política você se identifica, fez a escolha certa.");     
        break;
        
        case 5:
        JOptionPane.showMessageDialog(null,"Amante por países, cidades, "
                + "províncias,conhece o mundo a fora. Quando o assunto é "
                + "cultura, sabe de tudo.");    
        break; 
    }
    
    
    return boasvindasP ;
    
}     
    public static int boasvindasPersonagemM3(int personaM3){
        int boasvindasP  = 0;
    
        switch(personaM3){
            case 1:
            JOptionPane.showMessageDialog(null,"Então você é uma pessoa que "
                    + "gosta de curiosidades? Se você se identifica, "
                    + "fez a escolha certa."); 
                break;
        
            case 2:
            JOptionPane.showMessageDialog(null,"Quando o assunto é esporte o "
                    + "seu sorriso é mais reluzente que o sol Acho que alguém "
                    + "se identificou, você fez a escolha certa.");     
                break; 
        
            case 3:
            JOptionPane.showMessageDialog(null,"Quando é assunto de finanças, "
                    + "seus olhos brilham? "
                    + "Temos um amante de finanças aqui!");    
                break; 
        
            case 4:
            JOptionPane.showMessageDialog(null,"Então quer dizer que, quando o "
                + "assunto é empreender, seu coração bate mais forte?");     
                break;
        
            case 5:
            JOptionPane.showMessageDialog(null,"Amante por programação "
                    + "detectado. Vai um café?");    
            break; 
    }
    
    
    return boasvindasP ;
    
}
  
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoPersona = new javax.swing.ButtonGroup();
        Textpergunta = new javax.swing.JLabel();
        TextPersoM1 = new javax.swing.JRadioButton();
        TextPersoM4 = new javax.swing.JRadioButton();
        TextPersoM5 = new javax.swing.JRadioButton();
        TextPersoM2 = new javax.swing.JRadioButton();
        TextPersoM3 = new javax.swing.JRadioButton();
        btnVerMais = new javax.swing.JLabel();
        btnProximo = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Publico Masculino");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Textpergunta.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Textpergunta.setForeground(new java.awt.Color(255, 255, 255));
        Textpergunta.setText("Clique em \"Ver mais\" para liberar os personagens disponiveis para sua categoria");
        getContentPane().add(Textpergunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 670, -1));

        GrupoPersona.add(TextPersoM1);
        TextPersoM1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextPersoM1.setForeground(new java.awt.Color(255, 255, 255));
        TextPersoM1.setText("??????????????");
        TextPersoM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPersoM1ActionPerformed(evt);
            }
        });
        getContentPane().add(TextPersoM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 30));

        GrupoPersona.add(TextPersoM4);
        TextPersoM4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextPersoM4.setForeground(new java.awt.Color(255, 255, 255));
        TextPersoM4.setText("??????????????");
        getContentPane().add(TextPersoM4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, 30));

        GrupoPersona.add(TextPersoM5);
        TextPersoM5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextPersoM5.setForeground(new java.awt.Color(255, 255, 255));
        TextPersoM5.setText("??????????????");
        getContentPane().add(TextPersoM5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, 30));

        GrupoPersona.add(TextPersoM2);
        TextPersoM2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextPersoM2.setForeground(new java.awt.Color(255, 255, 255));
        TextPersoM2.setText("??????????????");
        getContentPane().add(TextPersoM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 30));

        GrupoPersona.add(TextPersoM3);
        TextPersoM3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextPersoM3.setForeground(new java.awt.Color(255, 255, 255));
        TextPersoM3.setText("??????????????");
        getContentPane().add(TextPersoM3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, 30));

        btnVerMais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Attack/icones/btnVerMais.png"))); // NOI18N
        btnVerMais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnVerMaisMouseReleased(evt);
            }
        });
        getContentPane().add(btnVerMais, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, -1, -1));

        btnProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Attack/icones/btnAvancar.png"))); // NOI18N
        btnProximo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnProximoMouseReleased(evt);
            }
        });
        getContentPane().add(btnProximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, -1, -1));

        Fundo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Fundo.setForeground(new java.awt.Color(255, 255, 255));
        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Attack/icones/TelaLogin.png"))); // NOI18N
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextPersoM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPersoM1ActionPerformed
       
    }//GEN-LAST:event_TextPersoM1ActionPerformed

    private void btnProximoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProximoMouseReleased
            TelaPacote1();
    }//GEN-LAST:event_btnProximoMouseReleased

    private void btnVerMaisMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMaisMouseReleased
        if(idadeMasculino <17){
                //MISTÉRIO
                Textpergunta.setText(Textpergunta.getText().replace("Clique em \"Ver mais\" para liberar os personagens disponiveis para sua categoria","      Clique em \"Selecionar\" para escolher seu personagem nessa essa aventura."));
                TextPersoM1.setText(TextPersoM1.getText().replace("??????????????","??????????????"));
                TextPersoM2.setText(TextPersoM2.getText().replace("??????????????","??????????????"));
                TextPersoM3.setText(TextPersoM3.getText().replace("??????????????","??????????????"));
                TextPersoM4.setText(TextPersoM4.getText().replace("??????????????","??????????????"));
                TextPersoM5.setText(TextPersoM5.getText().replace("??????????????","??????????????"));
                btnVerMais.setIcon(new ImageIcon(PublicoF.class.getResource("/br/com/Attack/icones/btnSelecionar.png")));
                
                
            }
            //PUBLICO A
            else if(idadeMasculino== 17 || idadeMasculino <=19){
                Textpergunta.setText(Textpergunta.getText().replace("Clique em \"Ver mais\" para liberar os personagens disponiveis para sua categoria","      Clique em \"Selecionar\" para escolher seu personagem nessa essa aventura."));
                TextPersoM1.setText(TextPersoM1.getText().replace("??????????????","O Sociólogo"));
                TextPersoM2.setText(TextPersoM2.getText().replace("??????????????","O Filosófico"));
                TextPersoM3.setText(TextPersoM3.getText().replace("??????????????","O Nerd"));
                TextPersoM4.setText(TextPersoM4.getText().replace("??????????????","O Físico"));
                TextPersoM5.setText(TextPersoM5.getText().replace("??????????????","O Linguístico"));
                btnVerMais.setIcon(new ImageIcon(PublicoF.class.getResource("/br/com/Attack/icones/btnSelecionar.png")));
                
                
                if(TextPersoM1.isSelected()){
                    personaM1=1;
                    PersonaUsuario = "O Sóciologo";
                }
                else if(TextPersoM2.isSelected()){
                    personaM1=2;
                    PersonaUsuario = "O Filosófico";
                }
                else if(TextPersoM3.isSelected()){
                   personaM1=3;
                   PersonaUsuario = "O Nerd";
                }
                else if(TextPersoM4.isSelected()){
                    personaM1=4;
                    PersonaUsuario = "O Físico";
                }
                else if(TextPersoM5.isSelected()){
                    personaM1=5;
                    PersonaUsuario = "O Linguístico";
                }
                
                int chamadapersona= boasvindasPersonagemM1(personaM1);
            }
            //PUBLICO B
            else if(idadeMasculino== 20 || idadeMasculino <=24){
                Textpergunta.setText(Textpergunta.getText().replace("Clique em \"Ver mais\" para liberar os personagens disponiveis para sua categoria","      Clique em \"Selecionar\" para escolher seu personagem nessa essa aventura."));
                TextPersoM1.setText(TextPersoM1.getText().replace("??????????????","O Antropólogo"));
                TextPersoM2.setText(TextPersoM2.getText().replace("??????????????","O Historiador"));
                TextPersoM3.setText(TextPersoM3.getText().replace("??????????????","O Intercambista"));
                TextPersoM4.setText(TextPersoM4.getText().replace("??????????????","O Geógrafo Político"));
                TextPersoM5.setText(TextPersoM5.getText().replace("??????????????","O Turista"));
                btnVerMais.setIcon(new ImageIcon(PublicoF.class.getResource("/br/com/Attack/icones/btnSelecionar.png")));
                
                
                if(TextPersoM1.isSelected()){
                    personaM2=1;
                    PersonaUsuario = "O Antropólogo";
                }
                else if(TextPersoM2.isSelected()){
                    personaM2=2;
                    PersonaUsuario = "O Historiador";
                }
                else if(TextPersoM3.isSelected()){
                   personaM2=3;
                   PersonaUsuario = "O Intercambista";
                }
                else if(TextPersoM4.isSelected()){
                    personaM2=4;
                    PersonaUsuario = "O Geógrafo Político";
                }
                else if(TextPersoM5.isSelected()){
                    personaM2=5;
                    PersonaUsuario = "O Turista";
                }
                int chamadapersona= boasvindasPersonagemM2(personaM2);
            }
            //PUBLICO C
            else if(idadeMasculino== 25 || idadeMasculino <=100){
                Textpergunta.setText(Textpergunta.getText().replace("Clique em \"Ver mais\" para liberar os personagens disponiveis para sua categoria","      Clique em \"Selecionar\" para escolher seu personagem nessa essa aventura."));
                TextPersoM1.setText(TextPersoM1.getText().replace("??????????????","O Curioso"));
                TextPersoM2.setText(TextPersoM2.getText().replace("??????????????","O Esportista"));
                TextPersoM3.setText(TextPersoM3.getText().replace("??????????????","O Financeiro"));
                TextPersoM4.setText(TextPersoM4.getText().replace("??????????????","O Empresário"));
                TextPersoM5.setText(TextPersoM5.getText().replace("??????????????","O Programador"));
                btnVerMais.setIcon(new ImageIcon(PublicoF.class.getResource("/br/com/Attack/icones/btnSelecionar.png")));
                
                
                if(TextPersoM1.isSelected()){
                    personaM3=1;
                    PersonaUsuario = "O Curioso";
                }
                else if(TextPersoM2.isSelected()){
                    personaM3=2;
                    PersonaUsuario = "O Esportista";
                }
                else if(TextPersoM3.isSelected()){
                   personaM3=3;
                   PersonaUsuario = "O Financeiro";
                }
                else if(TextPersoM4.isSelected()){
                    personaM3=4;
                    PersonaUsuario = "O Empresário";
                }
                else if(TextPersoM5.isSelected()){
                    personaM3=5;
                    PersonaUsuario = "O Programador";
                }
                int chamadapersona= boasvindasPersonagemM3(personaM3);
                
            }
    }//GEN-LAST:event_btnVerMaisMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/Pacote1/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pacote1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pacote1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pacote1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pacote1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PublicoM().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.ButtonGroup GrupoPersona;
    private javax.swing.JRadioButton TextPersoM1;
    private javax.swing.JRadioButton TextPersoM2;
    private javax.swing.JRadioButton TextPersoM3;
    private javax.swing.JRadioButton TextPersoM4;
    private javax.swing.JRadioButton TextPersoM5;
    private javax.swing.JLabel Textpergunta;
    private javax.swing.JLabel btnProximo;
    private javax.swing.JLabel btnVerMais;
    // End of variables declaration//GEN-END:variables


    
    
}
