/*
 * Essa tela de Splash carrega as informações necessárias para iniciar o jogo
 * 
 * 
 */
package br.com.Attack.formularios;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

/**
 *
 * @author Konex Soluções Tecnológicas.
 */
public class Splash extends javax.swing.JFrame {
    
    private void TelaLogin(){
        
	Login login = new Login();
        login.setVisible(true);
        dispose();		
    }

    /**
     * Creates new form Splash
     */
    public Splash() {
        UIManager.put("nimbusOrange", new Color(102, 0, 102));
        initComponents();
        new Thread(){
            
            public void run(){
                for(int i =0; i<101; i++){
                    try {
                        sleep(60);
                        BarraDeProgresso.setValue(i);
                        if(BarraDeProgresso.getValue() ==100){
                            TelaLogin();
                            dispose();
                        }                        
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Splash.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }                
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraDeProgresso = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraDeProgresso.setBackground(new java.awt.Color(255, 255, 255));
        BarraDeProgresso.setForeground(new java.awt.Color(0, 0, 0));
        BarraDeProgresso.setRequestFocusEnabled(false);
        BarraDeProgresso.setStringPainted(true);
        getContentPane().add(BarraDeProgresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 450, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Attack/icones/KonexLogo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Attack/icones/Splash.PNG"))); // NOI18N
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar BarraDeProgresso;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
