/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.Attack.formularios;

import java.awt.event.ActionListener;
import javafx.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Konex Soluções Tecnológicas.
 */
public class Tutorial extends javax.swing.JFrame {
    
    ActionListener TextTutorial_click;

    /**
     * Creates new form TelaInicio
     */
    
       private void TelaInformacaoPessoal(){
        
	InformacaoPessoal informacao = new InformacaoPessoal();
        informacao.setVisible(true);
        dispose();		
    }
    
    public Tutorial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // alterar jtext
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextPasso = new javax.swing.JLabel();
        TextTutorial = new javax.swing.JLabel();
        TextTutorial2 = new javax.swing.JLabel();
        TextTutorial3 = new javax.swing.JLabel();
        TextTutorial4 = new javax.swing.JLabel();
        TextTutorial5 = new javax.swing.JLabel();
        Passo2 = new javax.swing.JLabel();
        btnProximo = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tutorial");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextPasso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TextPasso.setForeground(new java.awt.Color(255, 255, 255));
        TextPasso.setText("1º Passo");
        getContentPane().add(TextPasso, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        TextTutorial.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        TextTutorial.setForeground(new java.awt.Color(255, 255, 255));
        TextTutorial.setText("            Attack of Questions é um jogo de perguntas");
        getContentPane().add(TextTutorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 550, -1));

        TextTutorial2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        TextTutorial2.setForeground(new java.awt.Color(255, 255, 255));
        TextTutorial2.setText("e respostas em diversos assuntos");
        getContentPane().add(TextTutorial2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 310, -1));

        TextTutorial3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        TextTutorial3.setForeground(new java.awt.Color(255, 255, 255));
        TextTutorial3.setText("              Para jogar, primeiro você escolhe");
        getContentPane().add(TextTutorial3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 470, -1));

        TextTutorial4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        TextTutorial4.setForeground(new java.awt.Color(255, 204, 0));
        TextTutorial4.setText("                  3 categorias de perguntas e o jogo");
        getContentPane().add(TextTutorial4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 460, -1));

        TextTutorial5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        TextTutorial5.setForeground(new java.awt.Color(255, 204, 0));
        TextTutorial5.setText("sorteará as questões, simples e fácil.");
        getContentPane().add(TextTutorial5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 440, -1));

        Passo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Attack/icones/btnVerMais.png"))); // NOI18N
        Passo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Passo2MouseClicked(evt);
            }
        });
        getContentPane().add(Passo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        btnProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Attack/icones/btnAvancar.png"))); // NOI18N
        btnProximo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnProximoMouseReleased(evt);
            }
        });
        getContentPane().add(btnProximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, -1, -1));

        Fundo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Fundo.setForeground(new java.awt.Color(255, 255, 255));
        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Attack/icones/TelaLogin.png"))); // NOI18N
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Passo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Passo2MouseClicked
        TextPasso.setText(TextPasso.getText().replace("1º Passo","2º Passo"));
        TextTutorial.setText(TextTutorial.getText().replace("            Attack of Questions é um jogo de perguntas","Após escolher as categorias confirme a partida para iniciar."));
        TextTutorial2.setText(TextTutorial2.getText().replace("e respostas em diversos assuntos","Cada partida inicia com um tempo de"));
        TextTutorial3.setText(TextTutorial3.getText().replace("              Para jogar, primeiro você escolhe","        resposta, inicialmente você tem um minuto "));
        TextTutorial4.setText(TextTutorial4.getText().replace("                  3 categorias de perguntas e o jogo","       porém de acordo com seu personagem você ganha"));
        TextTutorial5.setText(TextTutorial5.getText().replace("sorteará as questões, simples e fácil.","              um tempo adicional"));
        Passo2.setVisible(false);


    }//GEN-LAST:event_Passo2MouseClicked

    private void btnProximoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProximoMouseReleased
        TelaInformacaoPessoal();
    }//GEN-LAST:event_btnProximoMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tutorial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Passo2;
    private javax.swing.JLabel TextPasso;
    private javax.swing.JLabel TextTutorial;
    private javax.swing.JLabel TextTutorial2;
    private javax.swing.JLabel TextTutorial3;
    private javax.swing.JLabel TextTutorial4;
    private javax.swing.JLabel TextTutorial5;
    private javax.swing.JLabel btnProximo;
    // End of variables declaration//GEN-END:variables
}
