/*
 * Todos as partidas possuiem o cronometro no qual é fundamental  na jogabilidade
 * Nessa tela de ataque, fizemos a simulação de dois modos de ataque, ou seja,  
 * quando o usuário realiza um ataque. 
 */

package br.com.Attack.PerguntasPubA;

import br.com.Attack.formularios.Pacote1;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Konex Soluções Tecnológicas.
 */
public class Ataques extends javax.swing.JFrame {
    Random aleatorio = new Random();
    int ataqueADV=0;

    /** Creates new form Ataques */
    public Ataques() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QualAtaque = new javax.swing.JLabel();
        Ataque1 = new javax.swing.JLabel();
        Ataque2 = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        QualAtaque.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        QualAtaque.setForeground(new java.awt.Color(255, 255, 255));
        QualAtaque.setText("Qual ataque você deseja realizar?");
        getContentPane().add(QualAtaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 240, -1));

        Ataque1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Ataque1.setForeground(new java.awt.Color(255, 255, 255));
        Ataque1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Attack/icones/btnSegundos.png"))); // NOI18N
        Ataque1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Ataque1MouseReleased(evt);
            }
        });
        getContentPane().add(Ataque1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        Ataque2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Ataque2.setForeground(new java.awt.Color(255, 255, 255));
        Ataque2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Attack/icones/btnSortearResposta.png"))); // NOI18N
        Ataque2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Ataque2MouseReleased(evt);
            }
        });
        getContentPane().add(Ataque2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Attack/icones/TelaAzul.png"))); // NOI18N
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 170));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Ataque2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ataque2MouseReleased
        int numeroAleatorio = aleatorio.nextInt(4);
        
        if(numeroAleatorio==2){
            JOptionPane.showMessageDialog(null, "Seu adversário acertou a questão");
            ataqueADV++;
            dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Seu adversário Errou a questão");
            dispose();
        }

    }//GEN-LAST:event_Ataque2MouseReleased

    private void Ataque1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ataque1MouseReleased
        JOptionPane.showMessageDialog(null, "Foram retirados 30s do adversário!");
        dispose();
    }//GEN-LAST:event_Ataque1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ataques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ataques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ataques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ataques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ataques().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ataque1;
    private javax.swing.JLabel Ataque2;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel QualAtaque;
    // End of variables declaration//GEN-END:variables

}
