/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.Attack.PerguntasPubA;
import br.com.Attack.formularios.MenuPrincipal;

/**
 *
 * @author Alex
 */
public class PontuacaoFinal2 extends javax.swing.JFrame {
    private PerguntaFilo1 xx1 = new PerguntaFilo1();
    private int xp1 = xx1.XP1;
    private PerguntaFisi1 xx2 = new PerguntaFisi1();
    private int xp2 = xx2.XP2;
    private PerguntaMat1 xx3 = new PerguntaMat1();
    private int xp3 = xx3.XP3;
    private PerguntaPortugues1 xx4 = new PerguntaPortugues1();
    private int xp4 = xx4.XP4;
    private PerguntaSocio1 xx5 = new PerguntaSocio1();
    private int xp5 = xx5.XP5;
    private Ataques ataqueadv = new Ataques();
    private int ATADV = ataqueadv.ataqueADV;
    int xpADV=1;
    
    int XPFinal = xp1+xp2+xp3+xp4+xp5+ATADV;


    /**
     * Creates new form PontuacaoFinal
     */
    public PontuacaoFinal2() {
        initComponents();
        SeuXP.setText(String.valueOf(XPFinal));
        Adversario.setText(String.valueOf(xpADV));
        

    }
    private void TelaSair(){
        
	MenuPrincipal sair = new MenuPrincipal();
        sair.setVisible(true);
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SeuXP = new javax.swing.JLabel();
        Pontuacao = new javax.swing.JLabel();
        X = new javax.swing.JLabel();
        Adversario = new javax.swing.JLabel();
        Sair = new javax.swing.JButton();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SeuXP.setFont(new java.awt.Font("Tahoma", 3, 80)); // NOI18N
        SeuXP.setForeground(new java.awt.Color(255, 255, 255));
        SeuXP.setText("0");
        getContentPane().add(SeuXP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 70, 70));

        Pontuacao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Pontuacao.setForeground(new java.awt.Color(255, 255, 255));
        Pontuacao.setText("Pontuação Final");
        getContentPane().add(Pontuacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 150, -1));

        X.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        X.setForeground(new java.awt.Color(255, 255, 255));
        X.setText("X");
        getContentPane().add(X, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 40, 30));

        Adversario.setFont(new java.awt.Font("Tahoma", 3, 80)); // NOI18N
        Adversario.setForeground(new java.awt.Color(255, 255, 255));
        Adversario.setText("0");
        getContentPane().add(Adversario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 70, 70));

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        getContentPane().add(Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Attack/icones/TelaAzul.png"))); // NOI18N
        Fundo.setText("X");
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 130));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        TelaSair();
    }//GEN-LAST:event_SairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PontuacaoFinal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PontuacaoFinal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PontuacaoFinal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PontuacaoFinal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PontuacaoFinal2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adversario;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Pontuacao;
    private javax.swing.JButton Sair;
    private javax.swing.JLabel SeuXP;
    private javax.swing.JLabel X;
    // End of variables declaration//GEN-END:variables
}
